### ISSUE TITLE
Problem installing on Centos 6.5

### ISSUE THREAD

**Issue by jpike88** [c9/install#27]
Build fails on 6.5

> sqlite3@2.1.18 install /home/dev/.c9/node_modules/sqlite3
> node build.js

[sqlite3]: Checking for http://node-sqlite3.s3.amazonaws.com/Release/node_sqlite3-v2.1.a-node-v11-linux-x64.tar.gz
[sqlite3]: Downloaded to: /home/dev/.c9/tmp/node-sqlite3-Release/node_sqlite3-v2.1.a-node-v11-linux-x64.tar.gz
[sqlite3]: Checking for http://node-sqlite3.s3.amazonaws.com/Release/node_sqlite3-v2.1.a-node-v11-linux-x64.sha1.txt
[sqlite3]: Sha1sum matches! 822cc5103a2d6788ff2b6882ea98675a387bd45e
[sqlite3]: Extracting to lib/binding/Release
[sqlite3]: Testing the binary failed: "Command failed: 
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/dev/.c9/node_modules/sqlite3/lib/binding/Release/node-v11-linux-x64/node_sqlite3.node)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/dev/.c9/node_modules/sqlite3/lib/sqlite3.js:7:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
"

**Comment by jpike88** [comment]
Update: It seems SSH sort of works, but terminal does not work, and I get an error on load called "Missing collab dependencies". Other than that it seems to be working ok.

**Comment by javruben** [comment]
I think the error message indicates that glibc 2.14 is missing. You could try installing it manually and then rerunning the installer. Please let me know if that works and I'll add a check for that to the script.

**Comment by jpike88** [comment]
Apparently that is not recommended, as CentOS 6 uses glib 2.12 and that's a core system library.

What's weird is that everything seems to be working properly now...

**Comment by javruben** [comment]
Do you mean everything except the collaboration features?

**Comment by jpike88** [comment]
I did the whole process again on one of my servers (including deleting and reading the unix user that would be the SSH target) and while the auto-setup complained of not completing properly, it seems to be ok, I wasn't getting the 'missing collab dependencies' error anymore.

As for collab features, I haven't tested them yet but if I have issues I'll raise them of course. This just seems to be an issue with sqlite3 node, but Centos 6 is pretty damn common so that's probably a very bad thing.

**Comment by jpike88** [comment]
Nope, now it decided to start not working again.

Installing Collab Dependencies
npm http GET https://registry.npmjs.org/sqlite3
npm http 200 https://registry.npmjs.org/sqlite3
npm http GET https://registry.npmjs.org/sqlite3/-/sqlite3-2.1.18.tgz
npm http 200 https://registry.npmjs.org/sqlite3/-/sqlite3-2.1.18.tgz
npm http GET https://registry.npmjs.org/progress
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/tar.gz
npm http 200 https://registry.npmjs.org/progress
npm http 200 https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/progress/-/progress-1.0.1.tgz
npm http GET https://registry.npmjs.org/mkdirp/-/mkdirp-0.3.5.tgz
npm http 200 https://registry.npmjs.org/progress/-/progress-1.0.1.tgz
npm http 200 https://registry.npmjs.org/mkdirp/-/mkdirp-0.3.5.tgz
npm http 200 https://registry.npmjs.org/tar.gz
npm http GET https://registry.npmjs.org/tar.gz/-/tar.gz-0.1.1.tgz
npm http 200 https://registry.npmjs.org/tar.gz/-/tar.gz-0.1.1.tgz
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/fstream
npm http GET https://registry.npmjs.org/tar
npm http 200 https://registry.npmjs.org/fstream
npm http 200 https://registry.npmjs.org/tar
npm http 200 https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/fstream/-/fstream-0.1.31.tgz
npm http GET https://registry.npmjs.org/tar/-/tar-0.1.20.tgz
npm http GET https://registry.npmjs.org/commander/-/commander-1.1.1.tgz
npm http 200 https://registry.npmjs.org/fstream/-/fstream-0.1.31.tgz
npm http 200 https://registry.npmjs.org/tar/-/tar-0.1.20.tgz
npm http 200 https://registry.npmjs.org/commander/-/commander-1.1.1.tgz
npm http GET https://registry.npmjs.org/keypress
npm http 200 https://registry.npmjs.org/keypress
npm http GET https://registry.npmjs.org/keypress/-/keypress-0.1.0.tgz
npm http 200 https://registry.npmjs.org/keypress/-/keypress-0.1.0.tgz
npm http GET https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/rimraf
npm http 200 https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.0.tgz
npm http 200 https://registry.npmjs.org/inherits
npm http 200 https://registry.npmjs.org/rimraf
npm http 200 https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.0.tgz
npm http GET https://registry.npmjs.org/graceful-fs/-/graceful-fs-3.0.5.tgz
npm http GET https://registry.npmjs.org/inherits/-/inherits-2.0.1.tgz
npm http GET https://registry.npmjs.org/rimraf/-/rimraf-2.3.1.tgz
npm http 200 https://registry.npmjs.org/graceful-fs/-/graceful-fs-3.0.5.tgz
npm http 200 https://registry.npmjs.org/inherits/-/inherits-2.0.1.tgz
npm http 200 https://registry.npmjs.org/rimraf/-/rimraf-2.3.1.tgz
npm http GET https://registry.npmjs.org/block-stream
npm http 200 https://registry.npmjs.org/block-stream
npm http GET https://registry.npmjs.org/block-stream/-/block-stream-0.0.7.tgz
npm http 200 https://registry.npmjs.org/block-stream/-/block-stream-0.0.7.tgz
npm http GET https://registry.npmjs.org/glob
npm http 200 https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/glob/-/glob-4.5.1.tgz
npm http 200 https://registry.npmjs.org/glob/-/glob-4.5.1.tgz
npm http GET https://registry.npmjs.org/minimist
npm http GET https://registry.npmjs.org/inflight
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/once
npm http 200 https://registry.npmjs.org/inflight
npm http 200 https://registry.npmjs.org/once
npm http GET https://registry.npmjs.org/inflight/-/inflight-1.0.4.tgz
npm http GET https://registry.npmjs.org/once/-/once-1.3.1.tgz
npm http 200 https://registry.npmjs.org/inflight/-/inflight-1.0.4.tgz
npm http 200 https://registry.npmjs.org/once/-/once-1.3.1.tgz
npm http 200 https://registry.npmjs.org/minimist
npm http GET https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz
npm http 200 https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz
npm http 200 https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/minimatch/-/minimatch-2.0.1.tgz
npm http 200 https://registry.npmjs.org/minimatch/-/minimatch-2.0.1.tgz
npm http GET https://registry.npmjs.org/wrappy
npm http 200 https://registry.npmjs.org/wrappy
npm http GET https://registry.npmjs.org/wrappy/-/wrappy-1.0.1.tgz
npm http GET https://registry.npmjs.org/brace-expansion
npm http 200 https://registry.npmjs.org/wrappy/-/wrappy-1.0.1.tgz
npm http 200 https://registry.npmjs.org/brace-expansion
npm http GET https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.0.tgz
npm http 200 https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.0.tgz
npm http GET https://registry.npmjs.org/balanced-match
npm http GET https://registry.npmjs.org/concat-map
npm http 200 https://registry.npmjs.org/balanced-match
npm http 200 https://registry.npmjs.org/concat-map
npm http GET https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz
npm http GET https://registry.npmjs.org/balanced-match/-/balanced-match-0.2.0.tgz
npm http 200 https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz
npm http 200 https://registry.npmjs.org/balanced-match/-/balanced-match-0.2.0.tgz
> sqlite3@2.1.18 install /home/dev/.c9/node_modules/sqlite3
> node build.js
[sqlite3]: Checking for http://node-sqlite3.s3.amazonaws.com/Release/node_sqlite3-v2.1.a-node-v11-linux-x64.tar.gz
[sqlite3]: Downloaded to: /home/dev/.c9/tmp/node-sqlite3-Release/node_sqlite3-v2.1.a-node-v11-linux-x64.tar.gz
[sqlite3]: Checking for http://node-sqlite3.s3.amazonaws.com/Release/node_sqlite3-v2.1.a-node-v11-linux-x64.sha1.txt
[sqlite3]: Sha1sum matches! 822cc5103a2d6788ff2b6882ea98675a387bd45e
[sqlite3]: Extracting to lib/binding/Release
[sqlite3]: Testing the binary failed: "Command failed: 
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/dev/.c9/node_modules/sqlite3/lib/binding/Release/node-v11-linux-x64/node_sqlite3.node)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object. (/home/dev/.c9/node_modules/sqlite3/lib/sqlite3.js:7:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
"
[sqlite3]: Attempting source compile...
make: Entering directory `/home/dev/.c9/node_modules/sqlite3/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3071700/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3071700/sqlite3.o
Release/obj/gen/sqlite-autoconf-3071700/sqlite3.c: In function ‘porter_stemmer’:
Release/obj/gen/sqlite-autoconf-3071700/sqlite3.c:127209: warning: value computed is not used
Release/obj/gen/sqlite-autoconf-3071700/sqlite3.c:127213: warning: value computed is not used
Release/obj/gen/sqlite-autoconf-3071700/sqlite3.c:127226: warning: value computed is not used
Release/obj/gen/sqlite-autoconf-3071700/sqlite3.c:127231: warning: value computed is not used
Release/obj/gen/sqlite-autoconf-3071700/sqlite3.c:127237: warning: value computed is not used
Release/obj/gen/sqlite-autoconf-3071700/sqlite3.c:127242: warning: value computed is not used
Release/obj/gen/sqlite-autoconf-3071700/sqlite3.c:127251: warning: value computed is not used
Release/obj/gen/sqlite-autoconf-3071700/sqlite3.c:127258: warning: value computed is not used
Release/obj/gen/sqlite-autoconf-3071700/sqlite3.c:127301: warning: value computed is not used
Release/obj/gen/sqlite-autoconf-3071700/sqlite3.c:127321: warning: value computed is not used
  AR(target) Release/obj.target/deps/sqlite3.a
  COPY Release/sqlite3.a
  CXX(target) Release/obj.target/node_sqlite3/src/database.o
  CXX(target) Release/obj.target/node_sqlite3/src/node_sqlite3.o
  CXX(target) Release/obj.target/node_sqlite3/src/statement.o
  SOLINK_MODULE(target) Release/obj.target/node_sqlite3.node
  SOLINK_MODULE(target) Release/obj.target/node_sqlite3.node: Finished
  COPY Release/node_sqlite3.node
make: Leaving directory `/home/dev/.c9/node_modules/sqlite3/build'
[sqlite3]: Created: lib/binding/Release/node-v11-linux-x64
[sqlite3]: Installed in lib/binding/Release/node-v11-linux-x64/node_sqlite3.node
[sqlite3]: Sweet: "node_sqlite3.node" is valid, node-sqlite3 is now installed!
sqlite3@2.1.18 node_modules/sqlite3
├── progress@1.0.1
├── mkdirp@0.3.5
└── tar.gz@0.1.1 (commander@1.1.1, tar@0.1.20, fstream@0.1.31)
npm http GET https://registry.npmjs.org/sequelize
npm http 200 https://registry.npmjs.org/sequelize
npm http GET https://registry.npmjs.org/sequelize/-/sequelize-2.0.0-beta.0.tgz
npm http 200 https://registry.npmjs.org/sequelize/-/sequelize-2.0.0-beta.0.tgz
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/underscore.string
npm http GET https://registry.npmjs.org/lingo
npm http GET https://registry.npmjs.org/validator
npm http GET https://registry.npmjs.org/moment
npm http GET https://registry.npmjs.org/dottie
npm http GET https://registry.npmjs.org/toposort-class
npm http GET https://registry.npmjs.org/generic-pool
npm http GET https://registry.npmjs.org/promise
npm http GET https://registry.npmjs.org/sql
npm http GET https://registry.npmjs.org/commander
npm http 200 https://registry.npmjs.org/underscore.string
npm http 200 https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/underscore.string/-/underscore.string-2.3.3.tgz
npm http GET https://registry.npmjs.org/lodash/-/lodash-1.3.1.tgz
npm http 200 https://registry.npmjs.org/lodash/-/lodash-1.3.1.tgz
npm http 200 https://registry.npmjs.org/underscore.string/-/underscore.string-2.3.3.tgz
npm http 200 https://registry.npmjs.org/validator
npm http 200 https://registry.npmjs.org/dottie
npm http 200 https://registry.npmjs.org/promise
npm http GET https://registry.npmjs.org/dottie/-/dottie-0.0.8-0.tgz
npm http GET https://registry.npmjs.org/validator/-/validator-1.5.1.tgz
npm http GET https://registry.npmjs.org/promise/-/promise-3.2.0.tgz
npm http 200 https://registry.npmjs.org/dottie/-/dottie-0.0.8-0.tgz
npm http 200 https://registry.npmjs.org/promise/-/promise-3.2.0.tgz
npm http 200 https://registry.npmjs.org/validator/-/validator-1.5.1.tgz
npm http 200 https://registry.npmjs.org/lingo
npm http 200 https://registry.npmjs.org/moment
npm http 304 https://registry.npmjs.org/commander
npm http 200 https://registry.npmjs.org/toposort-class
npm WARN deprecated lingo@0.0.5: This project is abandoned
npm http GET https://registry.npmjs.org/lingo/-/lingo-0.0.5.tgz
npm http GET https://registry.npmjs.org/commander/-/commander-2.0.0.tgz
npm http GET https://registry.npmjs.org/moment/-/moment-2.1.0.tgz
npm http GET https://registry.npmjs.org/toposort-class/-/toposort-class-0.2.1.tgz
npm http 200 https://registry.npmjs.org/lingo/-/lingo-0.0.5.tgz
npm http 200 https://registry.npmjs.org/commander/-/commander-2.0.0.tgz
npm http 200 https://registry.npmjs.org/generic-pool
npm http 200 https://registry.npmjs.org/moment/-/moment-2.1.0.tgz
npm http 200 https://registry.npmjs.org/toposort-class/-/toposort-class-0.2.1.tgz
npm http GET https://registry.npmjs.org/generic-pool/-/generic-pool-2.0.4.tgz
npm http 200 https://registry.npmjs.org/generic-pool/-/generic-pool-2.0.4.tgz
npm http 200 https://registry.npmjs.org/sql
npm http GET https://registry.npmjs.org/sql/-/sql-0.26.0.tgz
npm http 200 https://registry.npmjs.org/sql/-/sql-0.26.0.tgz
npm http GET https://registry.npmjs.org/sliced
npm http 200 https://registry.npmjs.org/sliced
npm http GET https://registry.npmjs.org/sliced/-/sliced-0.0.5.tgz
npm http 200 https://registry.npmjs.org/sliced/-/sliced-0.0.5.tgz
sequelize@2.0.0-beta.0 node_modules/sequelize
├── promise@3.2.0
├── commander@2.0.0
├── toposort-class@0.2.1
├── dottie@0.0.8-0
├── generic-pool@2.0.4
├── lingo@0.0.5
├── validator@1.5.1
├── underscore.string@2.3.3
├── lodash@1.3.1
├── sql@0.26.0 (sliced@0.0.5)
└── moment@2.1.0
--2015-03-08 11:57:06--  https://raw.githubusercontent.com/c9/install/master/packages/sqlite3/linux/sqlite3.tar.gz
Resolving raw.githubusercontent.com... 103.245.222.133
Connecting to raw.githubusercontent.com|103.245.222.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4350866 (4.1M) [application/octet-stream]
Saving to: “sqlite3.tar.gz”
     0K .......... .......... .......... .......... ..........  1% 12.0M 0s
    50K .......... .......... .......... .......... ..........  2% 12.9M 0s
   100K .......... .......... .......... .......... ..........  3% 13.9M 0s
   150K .......... .......... .......... .......... ..........  4% 17.2M 0s
   200K .......... .......... .......... .......... ..........  5% 16.7M 0s
   250K .......... .......... .......... .......... ..........  7% 21.1M 0s
   300K .......... .......... .......... .......... ..........  8% 22.3M 0s
   350K .......... .......... .......... .......... ..........  9% 20.6M 0s
   400K .......... .......... .......... .......... .......... 10% 23.0M 0s
   450K .......... .......... .......... .......... .......... 11% 22.3M 0s
   500K .......... .......... .......... .......... .......... 12% 26.8M 0s
   550K .......... .......... .......... .......... .......... 14% 29.2M 0s
   600K .......... .......... .......... .......... .......... 15% 23.1M 0s
   650K .......... .......... .......... .......... .......... 16% 31.2M 0s
   700K .......... .......... .......... .......... .......... 17% 26.7M 0s
   750K .......... .......... .......... .......... .......... 18% 22.7M 0s
   800K .......... .......... .......... .......... .......... 20% 25.2M 0s
   850K .......... .......... .......... .......... .......... 21% 31.3M 0s
   900K .......... .......... .......... .......... .......... 22% 26.5M 0s
   950K .......... .......... .......... .......... .......... 23% 29.9M 0s
  1000K .......... .......... .......... .......... .......... 24% 29.9M 0s
  1050K .......... .......... .......... .......... .......... 25% 25.1M 0s
  1100K .......... .......... .......... .......... .......... 27% 30.7M 0s
  1150K .......... .......... .......... .......... .......... 28% 28.5M 0s
  1200K .......... .......... .......... .......... .......... 29% 23.9M 0s
  1250K .......... .......... .......... .......... .......... 30% 33.6M 0s
  1300K .......... .......... .......... .......... .......... 31% 29.7M 0s
  1350K .......... .......... .......... .......... .......... 32% 29.9M 0s
  1400K .......... .......... .......... .......... .......... 34% 31.5M 0s
  1450K .......... .......... .......... .......... .......... 35% 31.3M 0s
  1500K .......... .......... .......... .......... .......... 36% 31.2M 0s
  1550K .......... .......... .......... .......... .......... 37% 30.6M 0s
  1600K .......... .......... .......... .......... .......... 38% 27.7M 0s
  1650K .......... .......... .......... .......... .......... 40% 30.7M 0s
  1700K .......... .......... .......... .......... .......... 41% 29.6M 0s
  1750K .......... .......... .......... .......... .......... 42% 31.4M 0s
  1800K .......... .......... .......... .......... .......... 43% 35.6M 0s
  1850K .......... .......... .......... .......... .......... 44% 30.1M 0s
  1900K .......... .......... .......... .......... .......... 45% 27.0M 0s
  1950K .......... .......... .......... .......... .......... 47% 28.3M 0s
  2000K .......... .......... .......... .......... .......... 48% 30.2M 0s
  2050K .......... .......... .......... .......... .......... 49% 31.6M 0s
  2100K .......... .......... .......... .......... .......... 50% 25.3M 0s
  2150K .......... .......... .......... .......... .......... 51% 29.6M 0s
  2200K .......... .......... .......... .......... .......... 52% 24.9M 0s
  2250K .......... .......... .......... .......... .......... 54% 30.8M 0s
  2300K .......... .......... .......... .......... .......... 55% 38.6M 0s
  2350K .......... .......... .......... .......... .......... 56% 25.6M 0s
  2400K .......... .......... .......... .......... .......... 57% 29.2M 0s
  2450K .......... .......... .......... .......... .......... 58% 41.9M 0s
  2500K .......... .......... .......... .......... .......... 60% 44.3M 0s
  2550K .......... .......... .......... .......... .......... 61% 44.8M 0s
  2600K .......... .......... .......... .......... .......... 62% 38.9M 0s
  2650K .......... .......... .......... .......... .......... 63% 42.8M 0s
  2700K .......... .......... .......... .......... .......... 64% 40.1M 0s
  2750K .......... .......... .......... .......... .......... 65% 45.6M 0s
  2800K .......... .......... .......... .......... .......... 67% 43.2M 0s
  2850K .......... .......... .......... .......... .......... 68% 41.4M 0s
  2900K .......... .......... .......... .......... .......... 69% 48.3M 0s
  2950K .......... .......... .......... .......... .......... 70% 42.8M 0s
  3000K .......... .......... .......... .......... .......... 71% 43.8M 0s
  3050K .......... .......... .......... .......... .......... 72% 45.4M 0s
  3100K .......... .......... .......... .......... .......... 74% 43.1M 0s
  3150K .......... .......... .......... .......... .......... 75% 44.5M 0s
  3200K .......... .......... .......... .......... .......... 76% 40.2M 0s
  3250K .......... .......... .......... .......... .......... 77% 49.0M 0s
  3300K .......... .......... .......... .......... .......... 78% 45.1M 0s
  3350K .......... .......... .......... .......... .......... 80% 41.9M 0s
  3400K .......... .......... .......... .......... .......... 81% 43.5M 0s
  3450K .......... .......... .......... .......... .......... 82% 41.7M 0s
  3500K .......... .......... .......... .......... .......... 83% 45.4M 0s
  3550K .......... .......... .......... .......... .......... 84% 45.2M 0s
  3600K .......... .......... .......... .......... .......... 85% 41.5M 0s
  3650K .......... .......... .......... .......... .......... 87% 48.5M 0s
  3700K .......... .......... .......... .......... .......... 88% 42.7M 0s
  3750K .......... .......... .......... .......... .......... 89% 46.6M 0s
  3800K .......... .......... .......... .......... .......... 90% 43.1M 0s
  3850K .......... .......... .......... .......... .......... 91% 44.1M 0s
  3900K .......... .......... .......... .......... .......... 92% 45.2M 0s
  3950K .......... .......... .......... .......... .......... 94% 43.1M 0s
  4000K .......... .......... .......... .......... .......... 95% 43.4M 0s
  4050K .......... .......... .......... .......... .......... 96% 45.9M 0s
  4100K .......... .......... .......... .......... .......... 97% 41.7M 0s
  4150K .......... .......... .......... .......... .......... 98% 48.8M 0s
  4200K .......... .......... .......... .......... ........  100% 43.8M=0.1s
2015-03-08 11:57:06 (30.8 MB/s) - “sqlite3.tar.gz” saved [4350866/4350866]
sqlite3/
sqlite3/sqlite3.pc
sqlite3/sqlite3
sqlite3/sqlite3.pc.in
sqlite3/libsqlite3.la
sqlite3/sqlite3.lo
sqlite3/.libs/
sqlite3/.libs/sqlite3
sqlite3/.libs/libsqlite3.so.0.8.6
sqlite3/.libs/libsqlite3.so.0
sqlite3/.libs/libsqlite3.so
sqlite3/.libs/libsqlite3.la
sqlite3/.libs/libsqlite3.lai
sqlite3/.libs/lt-sqlite3
sqlite3/.libs/libsqlite3.a
sqlite3/.libs/sqlite3.o
sqlite3/sqlite3.1
sqlite3/.deps/
sqlite3/.deps/shell.Po
sqlite3/.deps/sqlite3.Plo
real	0m39.773s
user	0m30.166s
sys	0m3.448s
~/.c9/node_modules/.bin ~/.c9/lib
~/.c9/lib
Done.
One or more errors occured. Please try to resolve them and
restart Cloud9 or contact support@c9.io.

**Comment by jpike88** [comment]
Why on earth did you guys use a version of sqlite that requires a version of glibc that is only included on Centos 7??

**Comment by javruben** [comment]
@jpike88 I'm not sure about that - or what the implications are of that. Which version would be better to use?
