### ISSUE TITLE
when installing, ...Setting up VirtualEnv without global packages?

### ISSUE THREAD

**Issue by carrot93** [c9/install#40]
On ubuntu 14.04 
$curl -L https://raw.githubusercontent.com/c9/install/master/install.sh | bash
You have a global gyp installed. Setting up VirtualEnv without global pakages

And I try: git clone https://github.com/c9/core.git , and script/install-sdk.sh, same echo:
You have a global gyp installed. Setting up VirtualEnv without global pakages

Any idea?

**Comment by nightwing** [comment]
Could you try version from https://github.com/c9/install/pull/41

run

`curl -L https://raw.githubusercontent.com/c9/install/virtualenv/install.sh | bash `

**Comment by nightwing** [comment]
assuming #41 have fixed this.
