### ISSUE TITLE
collab server with sdk standalone

### ISSUE THREAD

**Issue by romanman** [c9/install#45]
How exactly I can set an environment 
for --collab option when starting a single 
sdk instance , pulled from here : 
https://github.com/c9/core
???

**Comment by romanman** [comment]
@javruben : after I set that one how 
to reference my ide there ?

**Comment by javruben** [comment]
I am not quite sure what you mean. The collab feature in the SDK is there purely for plugin development. Much of the backend is not included as it would require a database and that's too complex for the sdk. 

For testing purpose add `token=1` or `token=2` to the url to test as different users.

**Comment by romanman** [comment]
@javruben : thanks it looks like the tokens change
the icon of the user, not much more.

My question is if I do have option for the backend
or I nee to develop one myself if I want to use that 
feature ?

**Comment by romanman** [comment]
@javruben : after I have installed c9-vfs-extend, 
how the correct way start it ?

**Comment by javruben** [comment]
@romanman You don't need to start that. It's used by Cloud9. Simply start cloud9 with `./server.js --collab`

**Comment by romanman** [comment]
@javruben so it will recognize it installed on the server ?

**Comment by javruben** [comment]
I don't know what you mean.

**Comment by romanman** [comment]
@javruben : thanks for your time: the question is 
more wide: if I want to install vfs on one machine
and the cloud9 on a different , how I can manage
the communication between them.

**Comment by javruben** [comment]
This is not possible with the SDK version of Cloud9 - which is aimed for plugin development and personal use. 

For what you want you'll need our forthcoming on premise version of cloud9. If you are interested in that for your organization, please mail support@c9.io and a colleague will be in touch.

**Comment by romanman** [comment]
@javruben : thanks forwarded the mail, 
it will be great to try forthcoming version.
