### ISSUE TITLE
Terminal doesn't start

### ISSUE THREAD

**Issue by Senich** [c9/install#48]
Because of unknown reason my cloud9 terminal session doesn't start after project loading. It's not possible to type a single symbol. Looks like a GUI is frozen, but the left side of IDE with folders structure still responsive. I can navigate through folders and edit files. When I try to load a new terminal window via Alt+T combination I've got a new tab with icon of loading process and then nothing happens. In one of attempts after a while I got a message to configure some parameter with some value but it disappeared so fast so I can't describe what was that message about exactly. Looks like it's not only my very issue as I found out after some googling but there is now valid resolve of this problem.   Looking forward for your help, guys. Thanks!

**Comment by nightwing** [comment]
Does this happen on cloud9 ssh workspace or sdk?
Which OS you are using?

**Comment by Senich** [comment]
It happens on ssh workspace. I'm using Windows 7, Google Chrome 43.0.2357.81 m

**Comment by nightwing** [comment]
please email to support@c9.io telling your workspace name and username and we will help to debug this issue.

**Comment by Senich** [comment]
I'm sorry guys but it looks like the cause of  an issue is my local corporate network settings. I launch IDE from my iPhone, from my home pc and problem disappeard. Apparently some certain ports are being blocked or something. Anyway it's not your fault so I apologize for inconvinience.
