### ISSUE TITLE
Install c9dsk in opensuse 13.2

### ISSUE THREAD

**Issue by Elie33** [c9/install#49]
I try to install c9 in opensuse, and i get an error during the phase compiling tmux

* built new /home/Elie/.c9/local/share/terminfo
ln: impossible de créer le lien symbolique « /home/Elie/.c9/local/lib/terminfo »: Aucun fichier ou dossier de ce type
** could not sym-link /home/Elie/.c9/local/lib/terminfo for compatibility
installing std
installing stdcrt
installing vt100
installing vt300
/usr/bin/install -c ncurses-config /home/Elie/.c9/local/bin/ncurses5-config
make[1]: Leaving directory '/home/Elie/.c9/ncurses-5.9/misc'
:Compiling tmux...
:Configuring Tmux
configure: loading site script /usr/share/site/x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/home/Elie/.c9/tmux-1.9':
configure: error: C compiler cannot create executables
See `config.log' for more details

Thanks for your help

**Comment by nightwing** [comment]
try to install tmux via package manager, before installing c9sdk

**Comment by Elie33** [comment]
Installe it global or local?

**Comment by nightwing** [comment]
global, cloud9 tries to find tmux by running `which tmux` https://github.com/c9/install/blob/master/install.sh#L333 and simply creates a link to it if version of tmux is newer than 1.8

**Comment by Elie33** [comment]
npm install -g tmux --> install 1.3 version
Then install c9sdk with nearly the same error

:Compiling tmux...
:Configuring Tmux
configure: loading site script /usr/share/site/x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/home/Elie/.c9/tmux-1.9':
configure: error: C compiler cannot create executables
See `config.log' for more details

**Comment by Elie33** [comment]
which tmux
which: no tmux in (/home/Elie/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games:/usr/lib/mit/bin)

npm install tmux in directory
/usr/lib

**Comment by nightwing** [comment]
I was talking about https://github.com/tmux/tmux. Tmux module on npm seems to be a utility to manage tmux sessions and is not needed.
On ubuntu one can use `sudo apt-get install tmux` but i don't know what's the equivalent command for opensuse

**Comment by Elie33** [comment]
For opensuse it's zypper install tmux
Ok it's installed but now i have a problem with node-gyp

> pty.js@0.2.7-1 install /home/Elie/.c9/node_modules/pty.js
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory '/home/Elie/.c9/node_modules/pty.js/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
make: g++: commande introuvable
pty.target.mk:86: recipe for target 'Release/obj.target/pty/src/unix/pty.o' failed
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 127
make: Leaving directory '/home/Elie/.c9/node_modules/pty.js/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/Elie/.c9/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.16.7-21-desktop
gyp ERR! command "node" "/home/Elie/.c9/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/Elie/.c9/node_modules/pty.js
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.16.7-21-desktop
npm ERR! argv "/home/Elie/.c9/node/bin/node" "/home/Elie/.c9/node/bin/npm" "install" "pty.js@0.2.7-1"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.2.7-1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.2.7-1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/Elie/.c9/npm-debug.log

**Comment by nightwing** [comment]
you need install gcc
on ubuntu it can be installed from build-essential package 
For opensuse i found http://randomgeekery.org/tools/2014/06/22_what-is-build-essentials-for-opensuse.html, but not sure whether it's the best way.

**Comment by Elie33** [comment]
it 's good, c9sdk is now installed.
Thanks a lot for your support.
