### ISSUE TITLE
Urgent pty issue

### ISSUE THREAD

**Issue by bmbermn** [c9/install#87]
We are having an issue when attempting to install C9 we are getting:
--2018-04-09 19:21:19--  https://github.com/c9/install/releases/download/bin/pty-v4.8.7-linux-x64.tar.gz
Resolving github.com (github.com)... 192.30.255.112, 192.30.255.113
Connecting to github.com (github.com)|192.30.255.112|:443... connected.
HTTP request sent, awaiting response... 404 Not Found

Which we were able to confirm that pty is no longer available in this repo. Please update the installer to point to a new version or reload the repo with the version requested in the code. 

Thank you

**Comment by nightwing** [comment]
Updated. Thanks for reporting the issue!
